Update retailcrm.tpl
retailcrm/opencart-module pull request #102
Opened 2018-07-24 08:34 UTC by klaos27

2018-07-25 07:00 UTC, iyzoer requested changes

2018-07-25 07:00 UTC, iyzoer commented on src/upload/admin/view/template/extension/module/retailcrm.tpl
> +
Здесь три строки пустые.

2018-07-26 13:16 UTC, klaos27 commented on src/upload/admin/view/template/extension/module/retailcrm.tpl
> +
Как бы  убрал, но не знаю правильно ли.

2018-07-30 08:01 UTC, iyzoer commented on src/upload/admin/view/template/extension/module/retailcrm.tpl
> +
Прошу прощения, если непонятно описал проблему. Были пустые строки 219, 220 и 221. Их просто нужно было убрать, чтобы визуально не было большого пробела в коде. Вы удалили строки с кодом, из-за чего код на данный момент неработоспособный.

2018-07-30 12:45 UTC, klaos27 commented on src/upload/admin/view/template/extension/module/retailcrm.tpl
> +
Исправил

2018-07-30 14:10 UTC, merged