Test task OpenCart
retailcrm/opencart-module pull request #183
Opened 2020-07-03 09:24 UTC by SoldierOfHeart

Add Online Consultant

2020-07-14 10:41 UTC, Neur0toxine commented on src/upload/admin/controller/extension/module/retailcrm.php
> +
nit: Лишний перевод строки.

2020-07-14 10:41 UTC, Neur0toxine commented on src/upload/admin/controller/extension/module/retailcrm.php
> +
nit: Лишний перевод строки.

2020-07-14 10:41 UTC, Neur0toxine commented on src/upload/admin/language/ru-ru/extension/module/retailcrm.php
> +$_['entry_status']               = 'Использовать код для  online consultant';
Переводы нужны также и для английского и испанского.

2020-07-14 10:41 UTC, Neur0toxine commented on src/upload/admin/view/template/extension/module/retailcrm.tpl
> +                  </div>
nit: Имеет смысл заменить на чекбокс.

2020-07-14 10:41 UTC, Neur0toxine commented on src/upload/catalog/controller/extension/analytics/online_consultant.php
> +class ControllerExtensionAnalyticsOnlineConsultant extends Controller {
nit: Нет аннотации у класса. Также между объявлением класса и заголовком скрипта в данном случае должен быть перевод строки (при наличии аннотации - перед аннотацией), а открывающая скобка тела класса должна быть на новой строке.

2020-07-14 10:41 UTC, Neur0toxine commented on src/upload/catalog/controller/extension/analytics/online_consultant.php
> +
nit: Лишний перевод строки.

2020-07-14 10:41 UTC, Neur0toxine commented on src/upload/catalog/controller/extension/analytics/online_consultant.php
> +    public function index() {
nit: Нет аннотации у метода, открывающая скобка должна быть на новой строке.

2020-07-14 10:41 UTC, Neur0toxine commented on src/upload/catalog/controller/extension/analytics/online_consultant.php
> +        $moduleTitle = $this->retailcrm->getModuleTitle();
nit: Лучше группировать объявление переменных - так читаемость кода улучшится.

2020-07-14 10:41 UTC, Neur0toxine commented on src/upload/catalog/controller/extension/analytics/online_consultant.php
> +
nit: Лишний перевод строки.

2020-07-14 10:41 UTC, Neur0toxine commented on src/upload/catalog/controller/extension/analytics/online_consultant.php
> +
nit: Лишний перевод строки.

2020-08-03 11:59 UTC, Neur0toxine requested changes
Исправить указанные замечания.

2020-08-12 13:53 UTC, iyzoer commented on src/upload/admin/view/template/extension/module/retailcrm.tpl
> +                  </div>
на сколько помню везде в ос используется радио для настройки да/нет, и у нас модуле, смысла заменять на чекбокс здесь нет

2020-08-21 08:59 UTC, Neur0toxine requested changes

2020-08-21 08:59 UTC, Neur0toxine commented on src/upload/admin/controller/extension/module/retailcrm.php
> +            {
Открывающая кавычка тела условия должна быть на одной строке с условием, через пробел.

2020-08-21 08:59 UTC, Neur0toxine commented on src/upload/admin/controller/extension/module/retailcrm.php
> +            {
Открывающая кавычка тела условия должна быть на одной строке с условием, через пробел.

2020-08-21 11:15 UTC, merged