Added weight calculation based on product options
retailcrm/opencart-module pull request #221
Opened 2021-01-20 14:29 UTC by SoldierOfHeart

2021-01-26 07:56 UTC, iyzoer requested changes

2021-01-26 07:56 UTC, iyzoer commented on src/upload/admin/model/extension/retailcrm/icml.php
> +                $optionsProduct = $this->model_catalog_product->getProductOptions($product['product_id']);
зачем здесь повторно доставать опции для товара и повторно их перебирать?
обработка опций уже реализована [здесь](https://github.com/retailcrm/opencart-module/blob/master/src/upload/system/library/retailcrm/retailcrm.php#L129), там же реализован подсчет цены для каждой опции, думаю аналогично можно сделать и для веса там же.

2021-01-26 08:01 UTC, iyzoer commented on src/upload/admin/model/extension/retailcrm/icml.php
> +        while (current($options)) {
не совсем уместное, на мой взгляд, использование цикла `while` с `current`, `next`, `key`. Идентичного результата можно было бы добиться с использованием цикла `foreach`, хотя бы в целях однообразия. Такой подход больше нигде в коде модуля не используется.

2021-02-09 13:32 UTC, Neur0toxine requested changes

2021-02-09 13:32 UTC, Neur0toxine commented on src/upload/admin/model/extension/retailcrm/icml.php
> +                    $weightValue = $product['weight'] + $optionsValues['weight'];
Необходимо вернуть округление - ранее оно производилось.

2021-02-09 13:32 UTC, Neur0toxine commented on src/upload/system/library/retailcrm/retailcrm.php
> +
Лишний перевод строки.

2021-02-09 13:32 UTC, Neur0toxine commented on src/upload/system/library/retailcrm/retailcrm.php
> +        if($option['weight_prefix'] === '-') {
Между условным оператором и открывающей скобкой условия должен быть пробел.

2021-02-09 13:32 UTC, Neur0toxine commented on src/upload/system/library/retailcrm/retailcrm.php
> +    {
Стандарты OpenCart отличаются от PSR; здесь нужно открывающую фигурную скобку оставить на той же строке, что и объявление метода. Подробнее [тут](https://github.com/opencart/opencart/wiki/Coding-standards#new-lines).

2021-02-09 13:32 UTC, Neur0toxine commented on tests/system/RetailcrmTest.php
> +
Лишний перевод строки.

2021-02-09 13:39 UTC, iyzoer commented on src/upload/admin/model/extension/retailcrm/icml.php
> +                    $weightValue = $product['weight'] + $optionsValues['weight'];
в методе `getOffers` наверное лучше его убрать, а сюда уже для конечного результата добавить

2021-02-25 09:49 UTC, gwinn requested changes

2021-02-25 09:49 UTC, gwinn commented on src/upload/system/library/retailcrm/retailcrm.php
> +                            'weight' => $optionAttr['weight'] + $this->getWeightOption($optionValue)
Вот тут https://github.com/retailcrm/opencart-module/pull/221/files#diff-0cc4e2358f443a2d256cfed9744711c015e958cf4ef8ddd7334acd9f0a2464cdR154 используется округление, в а этой строке его почему-то нет

2021-02-25 09:49 UTC, gwinn commented on src/upload/system/library/retailcrm/retailcrm.php
> +                        'weight' => $this->getWeightOption($optionValue)
Тут тоже округление не применяется

2021-03-24 10:07 UTC, Neur0toxine approved these changes

2021-03-24 12:16 UTC, merged